version: '3'

services:
  ganache-cli:
    image: trufflesuite/ganache-cli:latest
    container_name: ganache-cli
    volumes:
      - "./db:/app/db"
    restart: always
    ports:
      - "8545:8545"
    entrypoint:
      - 'node'
      - '/app/ganache-core.docker.cli.js'
      - '--accounts=100'
      - '--deterministic'
      - '--db=/app/db'